export const LAHORE_AREAS = [
  "DHA Phase 1",
  "DHA Phase 2",
  "DHA Phase 3",
  "DHA Phase 4",
  "DHA Phase 5",
  "DHA Phase 6",
  "DHA Phase 7",
  "DHA Phase 8",
  "Gulberg I",
  "Gulberg II",
  "Gulberg III",
  "Model Town",
  "Garden Town",
  "Faisal Town",
  "Johar Town",
  "Wapda Town",
  "Canal Bank",
  "MM Alam Road",
  "Liberty Market",
  "Anarkali",
  "Mall Road",
  "Fortress Stadium",
  "Valencia Town",
  "Bahria Town",
  "Lake City",
  "EME Society",
  "Cavalry Ground",
  "Cantt",
  "Shadman",
  "Ichhra",
  "Samanabad",
  "Mozang",
  "Garhi Shahu",
  "Township",
  "Allama Iqbal Town",
  "Raiwind Road",
  "Thokar Niaz Baig",
  "Walton",
  "Shalimar",
  "Baghbanpura",
]
